# Generated by Django 4.0.5 on 2022-06-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kvantums', '0001_initial'),
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=200, verbose_name='Сертификат ученика')),
                ('name_ot', models.CharField(max_length=200, verbose_name='Имя и Отчество')),
                ('name_fam', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email_link', models.EmailField(max_length=254, null=True, verbose_name='Email ученика')),
                ('child_date_input', models.DateTimeField(verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('', 'Выберите вариант'), ('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], default='def', max_length=10, verbose_name='Пол')),
                ('school', models.CharField(max_length=200, verbose_name='Школа')),
                ('room', models.CharField(max_length=200, verbose_name='Класс')),
                ('inputs_name_legal_representative', models.CharField(max_length=500, verbose_name='Ф.И.О и данные законного представителя ребенка(ученика)')),
                ('name_legal_representativeTelephone', models.CharField(max_length=500, verbose_name='Телефон для связи законного представителя ребенка(ученика)')),
                ('comments', models.CharField(max_length=1000, verbose_name='Комментарии к ученику')),
                ('exp', models.CharField(default=0, max_length=1000, verbose_name='Опыт ученика(Для внетреннего магазина)')),
                ('coin', models.CharField(default=0, max_length=1000, verbose_name='Монеты ученика(Для внетреннего магазина)')),
                ('student_checked', models.BooleanField(default=False, verbose_name='Ученик проверен')),
                ('student_deleted', models.BooleanField(default=False, verbose_name='Ученик не активен(Выпускник)')),
                ('kvantum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Квантум')),
                ('organization_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personals.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_time', models.DateTimeField(verbose_name='Учебное время группы')),
                ('arrows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Квантум')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personals.teacher', verbose_name='Выберите преподавателя')),
            ],
            options={
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='StudentRang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=100, verbose_name='Ранг ученика')),
            ],
            options={
                'verbose_name_plural': 'Ранг ученика',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='rang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentrang', verbose_name='Ранг ученика'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personals.teacher', verbose_name='Преподаватель'),
        ),
    ]
