# Generated by Django 4.0.5 on 2022-06-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personals', '0002_alter_organization_options_alter_teacher_options_and_more'),
        ('kvantums', '0002_alter_kvantum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=100, verbose_name='Ранг ученика')),
            ],
            options={
                'verbose_name_plural': 'Ранг ученика',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=200, verbose_name='Сертификат ученика')),
                ('name_ot', models.CharField(max_length=200, verbose_name='Имя и Отчество')),
                ('name_fam', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email_link', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ученика')),
                ('child_date_input', models.DateTimeField(verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('', 'Выберите вариант'), ('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], default='def', max_length=10, verbose_name='Пол')),
                ('school', models.CharField(max_length=200, verbose_name='Школа')),
                ('room', models.CharField(max_length=200, verbose_name='Класс')),
                ('inputs_name_legal_representative', models.CharField(max_length=500, verbose_name='Ф.И.О и данные законного представителя ребенка(ученика)')),
                ('name_legal_representativeTelephone', models.CharField(max_length=500, verbose_name='Телефон для связи законного представителя ребенка(ученика)')),
                ('comments', models.CharField(max_length=1000, verbose_name='Комментарии к ученику')),
                ('exp', models.CharField(default=0, max_length=1000, verbose_name='Опыт ученика(Для внетреннего магазина)')),
                ('coin', models.CharField(default=0, max_length=1000, verbose_name='Монеты ученика(Для внетреннего магазина)')),
                ('student_checked', models.BooleanField(default=False)),
                ('student_deleted', models.BooleanField(default=False)),
                ('kvantum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Квантум')),
                ('organization_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personals.organization', verbose_name='Организация')),
                ('rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentrang', verbose_name='Ранг ученика')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personals.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
