# Generated by Django 4.0.5 on 2022-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_link',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_checked',
            field=models.BooleanField(default=False, verbose_name='Ученик проверен'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_deleted',
            field=models.BooleanField(default=False, verbose_name='Ученик не активен(Выпускник)'),
        ),
    ]
