# Generated by Django 4.0.5 on 2022-12-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvantums', '0002_alter_kvantum_options_alter_kvantum_description_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студента', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='studentgrouproom',
            options={'verbose_name': 'Группу студента', 'verbose_name_plural': 'Группы студента'},
        ),
        migrations.AlterModelOptions(
            name='studentrang',
            options={'verbose_name': 'Ранг ученика', 'verbose_name_plural': 'Ранг ученика'},
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='group_name',
            field=models.CharField(help_text='Группа 4', max_length=100, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='child_date_input',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.TextField(max_length=1000, verbose_name='Комментарии к ученику'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='arrows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_time',
            field=models.TimeField(verbose_name='Учебное время группы'),
        ),
    ]
