# Generated by Django 4.0.5 on 2023-03-24 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentgrouproom_options_studentteacherreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacherreport',
            name='fact_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
