# Generated by Django 4.0.5 on 2022-06-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_alter_organization_options_alter_teacher_options_and_more'),
        ('kvantums', '0002_alter_kvantum_image'),
        ('students', '0002_alter_student_email_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_time', models.DateTimeField(verbose_name='Учебное время группы')),
                ('arrows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Квантум')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personals.teacher', verbose_name='Выберите преподавателя')),
            ],
            options={
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup')),
            ],
        ),
    ]
