# Generated by Django 4.0.5 on 2022-12-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_studentgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentShoolName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shool_name', models.CharField(max_length=200, verbose_name='Введите название школы')),
            ],
            options={
                'verbose_name': 'Название школы',
                'verbose_name_plural': 'Название школы',
            },
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Всего групп', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='studentrang',
            name='rang',
            field=models.CharField(max_length=200, verbose_name='Ранг ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='students.studentshoolname', verbose_name='Школа'),
        ),
    ]
