# Generated by Django 4.0.5 on 2023-03-24 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentteacherreport_fact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacherreport',
            name='fact_date',
        ),
        migrations.AddField(
            model_name='studentteacherreport',
            name='fact_date_report',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Фактическая дата'),
        ),
    ]
