# Generated by Django 4.0.5 on 2023-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentteacherreport_group_time_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacherreport',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AddField(
            model_name='studentteacherreport',
            name='student_checked',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
