# Generated by Django 4.0.5 on 2023-03-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentteacherreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacherreport',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты (посещаемость)'},
        ),
        migrations.AlterField(
            model_name='studentteacherreport',
            name='group_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup', verbose_name='Выберите группу'),
        ),
    ]
