# Generated by Django 4.0.5 on 2022-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvantums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvantum',
            options={'verbose_name': 'Квантум', 'verbose_name_plural': 'Квантумы'},
        ),
        migrations.AlterField(
            model_name='kvantum',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Описание направления'),
        ),
        migrations.AlterField(
            model_name='kvantum',
            name='description_full',
            field=models.TextField(max_length=5500, verbose_name='Описание направления - полное'),
        ),
    ]
