# Generated by Django 4.0.5 on 2022-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvantums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantum',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
