# Generated by Django 4.0.5 on 2022-06-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kvantums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/teachers')),
                ('link_web_main', models.CharField(max_length=200, verbose_name='Ссылка на персональную страниц')),
                ('link_web_facebook', models.CharField(max_length=500, verbose_name='Ссылка на страницу FaceBook')),
                ('link_web_twitter', models.CharField(max_length=500, verbose_name='Ссылка на страницу Twitter')),
                ('link_web_skype', models.CharField(max_length=500, verbose_name='Ссылка на страницу Skype')),
                ('link_web_google', models.CharField(max_length=500, verbose_name='Ссылка на страницу Google')),
                ('link_web_vk', models.CharField(max_length=500, verbose_name='Ссылка на страницу VK')),
                ('teacher_desc', models.CharField(max_length=500, verbose_name='Описание, образоваине и т.д')),
                ('kvantum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Квантум')),
                ('organization_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personals.organization', verbose_name='Организация')),
                ('teacher_full_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выберите пользователя из базы(Преподавателя)')),
            ],
        ),
    ]
