# Generated by Django 4.0.5 on 2022-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='images',
            field=models.ImageField(upload_to='images/teachers', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_facebook',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу FaceBook'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_google',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу Google'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_main',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на персональную страниц'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_skype',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу Skype'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_twitter',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу Twitter'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_web_vk',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу VK'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание, образоваине и т.д'),
        ),
    ]
