# Generated by Django 4.0.5 on 2023-03-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvantums', '0003_alter_kvantum_options_kvantum_program_doc'),
        ('personals', '0004_alter_event_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, upload_to='images/staff/photo/', verbose_name='Фотография работника'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kvantum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvantums.kvantum', verbose_name='Направление'),
        ),
    ]
